### ISSUE TITLE
Update Rubocop to latest

### ISSUE THREAD

**Issue by afiune** [fnichol/finstyle#8]
We need to update rubocop to the latest version because we are seeing this errors on Test-kitchen unit testing:
```
[3] pry(main)> RuboCop::RakeTask.new(:style) do |task|
[3] pry(main)*   task.options += ["--display-cop-names", "--no-color"]
[3] pry(main)* end
NoMethodError: undefined method `last_comment' for #<Rake::Application:0x007fbabc65bb38>
from /opt/chefdk/embedded/lib/ruby/gems/2.3.0/gems/rubocop-0.32.1/lib/rubocop/rake_task.rb:23:in `initialize'
```

We need at least version `0.38.0` or above: https://github.com/bbatsov/rubocop/blob/master/relnotes/v0.38.0.md#bug-fixes

To be able to consume:
>Replace Rake::TaskManager#last_comment with Rake::TaskManager#last_description for Rake 11 compatibility. (@tbrisker)

**Comment by schisamo** [comment]
Perhaps we should just move test-kitchen over to using [chefstyle](https://github.com/chef/chefstyle)? `chefstyle` was directly inspired by `finstyle`.

/cc @thommay @fnichol

**Comment by afiune** [comment]
@schisamo Should I just require chefstyle instead of finstyle? 👍

**Comment by schisamo** [comment]
That should do it, you may have a few style bugs to fix but can do all that in the same branch/pr.

**Comment by afiune** [comment]
Awesome thank man... !!! 👍
